name: Website
on:
  push:
    branches:
      - gh-pages
  pull_request: []
jobs:
  build-website:
    if: ${{ !endsWith(github.repository, '/styles') }}
    runs-on: ubuntu-20.04
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the lesson
        uses: actions/checkout@v2
        with:
          path: "workshop-template"
          fetch-depth: 0
          #ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install GitHub Pages, Bundler, and kramdown gems
        run: |
          gem install github-pages bundler kramdown kramdown-parser-gfm

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests
          python3 -m pip install -r workshop-template/requirements.txt

      - name: Look for R-markdown files
        id: check-rmd
        run: |
          echo "::set-output name=count::$(shopt -s nullglob; files=($(find . -iname '*.Rmd')); echo ${#files[@]})"

      - name: Set up R
        if: steps.check-rmd.outputs.count != 0
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Cache R packages
        if: steps.check-rmd.outputs.count != 0
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install needed packages
        if: steps.check-rmd.outputs.count != 0
        run: |
          install.packages(setdiff(c('remotes', 'rprojroot', 'renv', 'desc', 'rmarkdown', 'knitr'), rownames(installed.packages())))
        shell: Rscript {0}

      - name: Query dependencies
        if: steps.check-rmd.outputs.count != 0
        run: |
          source('bin/dependencies.R')
          deps <- identify_dependencies()
          create_description(deps)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install system dependencies for R packages
        if: steps.check-rmd.outputs.count != 0
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')

      - name: Get/Update git submodules
        run: |
          cd workshop-template/
          python bin/get_submodules.py
          cd -

      - name: Create schedules
        run: |
          cd workshop-template/
          python bin/get_schedules.py

      - name: Commit and Push
        # if: ${{ !env.ACT }}
        run: |
          cd workshop-template/
          # setup git
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A ./_includes/ ./collections/ ./fig/ ./slides/
          git commit --allow-empty -m "[Github Actions] render website (via ${{ github.sha }})"
          git push origin gh-pages
          # return
          cd -

      # waiting for https://github.com/carpentries/styles/issues/551
      # to be addressed
      # - run: make lesson-check-all
      #   if: always()
